author: NJUCSE17
description: problem solving
keyword: 
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
# Projects: /project/
 About: /about/

# highlight
highlight:
  default

comment: true
  
# catalog
catalog: true

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
